[package]
name = "rust_exif"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.4.4", features = ["derive"] }
kamadak-exif = "0.5.5"
rexiv2 = "0.10.0"
xmp_toolkit = "1.8.1"
